# Generated by Django 4.1.5 on 2023-03-02 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_courseallocation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='program',
            new_name='department',
        ),
    ]
