# Generated by Django 4.1.5 on 2023-03-02 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_student_department'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='course',
        ),
    ]
