# Generated by Django 4.1.5 on 2023-03-06 09:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_remove_student_period'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='academic_year',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='user.academics'),
            preserve_default=False,
        ),
    ]
