# Generated by Django 4.1.5 on 2023-03-06 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_roll'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculties',
            name='faculty_code',
            field=models.CharField(max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='faculties',
            name='faculty_name',
            field=models.CharField(max_length=150),
        ),
    ]
