# Generated by Django 4.1.5 on 2023-03-06 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_alter_faculties_faculty_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academics',
            name='academic_year',
            field=models.DateTimeField(),
        ),
    ]
