# Generated by Django 4.1.5 on 2023-03-06 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_alter_academics_academic_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academics',
            name='academic_status',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='academics',
            name='academic_year',
            field=models.DateField(),
        ),
    ]
