# Generated by Django 4.1.5 on 2023-03-06 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0017_course_is_elective_course_semester'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Levels',
        ),
    ]
