# Generated by Django 4.1.5 on 2023-03-10 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0027_remove_semester_session_semester_is_current_semester'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='semester',
            name='next_semester_begins',
        ),
    ]
