# Generated by Django 4.1.5 on 2023-03-10 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0028_remove_semester_next_semester_begins'),
    ]

    operations = [
        migrations.AddField(
            model_name='semester',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
