# Generated by Django 4.1.5 on 2023-03-10 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0029_semester_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='semester',
            name='semester_code',
            field=models.CharField(max_length=200, unique=True, verbose_name='semester_code'),
        ),
    ]
