# Generated by Django 4.1.5 on 2023-03-13 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0030_alter_semester_semester_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='academics',
            name='academic_year',
        ),
    ]
