# Generated by Django 4.1.5 on 2023-03-13 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0031_remove_academics_academic_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='academics',
            name='academic_year',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
