# Generated by Django 4.1.5 on 2023-03-13 08:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0032_academics_academic_year'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CourseAllocation',
            new_name='DepartmentAllocation',
        ),
        migrations.RemoveField(
            model_name='course',
            name='course_id',
        ),
        migrations.RemoveField(
            model_name='course',
            name='credit',
        ),
        migrations.RemoveField(
            model_name='course',
            name='department',
        ),
        migrations.RemoveField(
            model_name='course',
            name='faculty',
        ),
        migrations.RemoveField(
            model_name='course',
            name='is_elective',
        ),
        migrations.RemoveField(
            model_name='course',
            name='level',
        ),
        migrations.RemoveField(
            model_name='course',
            name='semester',
        ),
        migrations.RemoveField(
            model_name='course',
            name='title',
        ),
        migrations.RemoveField(
            model_name='course',
            name='year',
        ),
        migrations.RemoveField(
            model_name='department',
            name='department_code',
        ),
        migrations.RemoveField(
            model_name='department',
            name='description',
        ),
        migrations.RemoveField(
            model_name='department',
            name='status',
        ),
        migrations.RemoveField(
            model_name='departmentallocation',
            name='courses',
        ),
        migrations.RemoveField(
            model_name='subjects',
            name='course',
        ),
        migrations.AddField(
            model_name='course',
            name='course_code',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='course_title',
            field=models.CharField(default=1, max_length=150, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='department',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='user.course'),
        ),
        migrations.AddField(
            model_name='department',
            name='credit',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='department',
            name='department_id',
            field=models.CharField(blank=True, max_length=200, unique=True, verbose_name='course_id'),
        ),
        migrations.AddField(
            model_name='department',
            name='faculty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.faculties'),
        ),
        migrations.AddField(
            model_name='department',
            name='is_elective',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='department',
            name='level',
            field=models.CharField(choices=[('Bachelor', 'Bachelor Degree'), ('Master', 'Master Degree')], max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='department',
            name='semester',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.semester'),
        ),
        migrations.AddField(
            model_name='department',
            name='year',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4')], default=0),
        ),
        migrations.AddField(
            model_name='departmentallocation',
            name='department',
            field=models.ManyToManyField(related_name='allocated_course', to='user.department'),
        ),
        migrations.AlterField(
            model_name='department',
            name='title',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
