# Generated by Django 4.1.5 on 2023-03-13 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0033_rename_courseallocation_departmentallocation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_code',
            field=models.CharField(blank=True, max_length=200, unique=True, verbose_name='course_code'),
        ),
    ]
