# Generated by Django 4.1.5 on 2023-03-14 05:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0039_rename_subjects_subject'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubjectAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lecturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocated_lecturer', to=settings.AUTH_USER_MODEL)),
                ('subject', models.ManyToManyField(related_name='allocated_subjects', to='user.subject')),
            ],
        ),
        migrations.DeleteModel(
            name='DepartmentAllocation',
        ),
    ]
