# Generated by Django 4.1.5 on 2023-03-14 07:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0040_subjectallocation_delete_departmentallocation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='takencourse',
            name='course',
        ),
        migrations.AddField(
            model_name='takencourse',
            name='subject',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='taken_subjects', to='user.subject'),
            preserve_default=False,
        ),
    ]
