# Generated by Django 4.1.5 on 2023-03-14 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0041_remove_takencourse_course_takencourse_subject'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TakenCourse',
            new_name='TakenSubject',
        ),
    ]
