# Generated by Django 4.1.5 on 2023-03-17 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0042_rename_takencourse_takensubject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subjectallocation',
            name='subject',
        ),
    ]
