# Generated by Django 4.1.5 on 2023-03-17 07:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0044_subjectallocation_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjectallocation',
            name='lecturer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocated_lecturer', to='user.teacher'),
        ),
    ]
