# Generated by Django 4.1.5 on 2023-03-20 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0046_uploadfiles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadfiles',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.subject'),
        ),
    ]
