# Generated by Django 4.1.5 on 2023-03-21 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0050_remove_subject_teacher_subject_course'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TakenSubject',
            new_name='StudentTakenSubject',
        ),
    ]
